---
name: openQA test
# yamllint disable-line rule:truthy
on:
  pull_request_target:
  push:
  # Note how this runs on:pull_request_target and not on:pull_request!
  # The difference is that this runs always with the context of the master
  # branch. This is necessary to allow accessing the API credential secrets.
  workflow_dispatch:
env:
  OPENQA_HOST: ${{ secrets.OPENQA_URL }}
  OPENQA_API_KEY: ${{ secrets.OPENQA_API_KEY }}
  OPENQA_API_SECRET: ${{ secrets.OPENQA_API_SECRET }}
  GH_REPO: ${{ github.event.pull_request.head.repo.full_name }}
  GH_REF: ${{ github.event.pull_request.head.ref }}

jobs:
  trigger_and_monitor_openqa:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/containers/tumbleweed:client
    steps:
      - uses: actions/checkout@v3
      - name: Get latest build
        id: latest_build
        run: >-
          build=$(openqa-cli api
          --host ${OPENQA_HOST:-https://openqa.opensuse.org}
          job_groups/1/build_results only_tagged=1
          | jq -r '[ .build_results[] | select(.tag.description=="published") | .build ][0]'
          )

          echo "build: $build"


          image=$(openqa-cli api --host ${OPENQA_HOST:-https://openqa.opensuse.org} assets
          | jq -r '[.assets[]|select(.name | test("Tumbleweed-x86_64-'"$build"'-minimalx@64bit\\."; "")) | select(.size != null)] | .[0] | .name')

          echo "image: $image"

          echo build=$build >> "$GITHUB_OUTPUT"

          echo "image=$image" >> "$GITHUB_OUTPUT"

      - name: Link to test result overview page
        run: >-
          build=$(tr '/' ':' <<<"$GH_REPO#$GH_REF");
          build=$(perl -e 'use Mojo::Util; print(Mojo::Util::url_escape($ARGV[0]))' "$build");
          echo "${OPENQA_HOST:-https://openqa.opensuse.org}/tests/overview?flavor=dev&build=$build"
      - name: Trigger and monitor openQA test
        run: >-
          echo openqa-cli schedule
          --monitor
          --host "${OPENQA_HOST:-https://openqa.opensuse.org}/"
          --apikey "$OPENQA_API_KEY" --apisecret "$OPENQA_API_SECRET"
          --param-file SCENARIO_DEFINITIONS_YAML=scenario-definitions.yaml
          DISTRI=openQA VERSION=Tumbleweed FLAVOR=dev ARCH=x86_64
          HDD_1=${{ steps.latest_build.outputs.image }}
          BUILD=$(tr '/' ':' <<<"$GH_REPO#$GH_REF") _GROUP_ID=0
          CASEDIR="$GITHUB_SERVER_URL/$GH_REPO.git#$GH_REF"
